# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'cadastro_membros.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QLabel, QLineEdit, QMainWindow,
    QPushButton, QRadioButton, QSizePolicy, QVBoxLayout,
    QWidget)
import icones_rc

class Ui_AD_COSTA_VERDE(object):
    def setupUi(self, AD_COSTA_VERDE):
        if not AD_COSTA_VERDE.objectName():
            AD_COSTA_VERDE.setObjectName(u"AD_COSTA_VERDE")
        AD_COSTA_VERDE.setEnabled(True)
        AD_COSTA_VERDE.resize(1025, 239)
        AD_COSTA_VERDE.setStyleSheet(u"background-color: rgb(0, 85, 127);")
        self.centralwidget = QWidget(AD_COSTA_VERDE)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(190, 70, 81, 16))
        font = QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setStyleSheet(u"color: rgb(0, 170, 0);")
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(610, 120, 91, 16))
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(u"color: rgb(0, 170, 0);")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(610, 70, 101, 16))
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(u"color: rgb(0, 170, 0);")
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(610, 170, 71, 16))
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(u"color: rgb(0, 170, 0);")
        self.lineEdit_1 = QLineEdit(self.centralwidget)
        self.lineEdit_1.setObjectName(u"lineEdit_1")
        self.lineEdit_1.setGeometry(QRect(190, 90, 341, 23))
        self.lineEdit_1.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_4 = QLineEdit(self.centralwidget)
        self.lineEdit_4.setObjectName(u"lineEdit_4")
        self.lineEdit_4.setGeometry(QRect(610, 140, 151, 23))
        self.lineEdit_4.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_2 = QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName(u"lineEdit_2")
        self.lineEdit_2.setGeometry(QRect(610, 90, 251, 23))
        self.lineEdit_2.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_3 = QLineEdit(self.centralwidget)
        self.lineEdit_3.setObjectName(u"lineEdit_3")
        self.lineEdit_3.setGeometry(QRect(610, 190, 241, 23))
        self.lineEdit_3.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_5 = QLineEdit(self.centralwidget)
        self.lineEdit_5.setObjectName(u"lineEdit_5")
        self.lineEdit_5.setGeometry(QRect(420, 180, 115, 23))
        self.lineEdit_5.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit_6 = QLineEdit(self.centralwidget)
        self.lineEdit_6.setObjectName(u"lineEdit_6")
        self.lineEdit_6.setGeometry(QRect(190, 180, 221, 23))
        self.lineEdit_6.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(420, 160, 101, 16))
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(u"color: rgb(0, 170, 0);")
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(190, 160, 42, 16))
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(u"color: rgb(0, 170, 0);")
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(900, 210, 93, 28))
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setItalic(False)
        font1.setUnderline(False)
        font1.setStrikeOut(False)
        self.pushButton.setFont(font1)
        self.pushButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton.setStyleSheet(u"background-color: rgb(181, 172, 177);")
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(0, 210, 91, 28))
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        font2.setItalic(False)
        font2.setUnderline(True)
        self.pushButton_2.setFont(font2)
        self.pushButton_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet(u"background-color: rgb(181, 172, 177);")
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(230, 30, 431, 31))
        font3 = QFont()
        font3.setPointSize(20)
        font3.setBold(True)
        self.label_8.setFont(font3)
        self.label_8.setStyleSheet(u"color: rgb(0, 170, 0);")
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(190, 120, 181, 16))
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(u"color: rgb(0, 170, 0);")
        self.lineEdit_7 = QLineEdit(self.centralwidget)
        self.lineEdit_7.setObjectName(u"lineEdit_7")
        self.lineEdit_7.setGeometry(QRect(190, 140, 181, 22))
        self.lineEdit_7.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.lineEdit = QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setGeometry(QRect(410, 140, 191, 22))
        self.lineEdit.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(410, 120, 91, 16))
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(u"color: rgb(0, 170, 0);")
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(880, 40, 134, 155))
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.radioButton_1 = QRadioButton(self.layoutWidget)
        self.radioButton_1.setObjectName(u"radioButton_1")
        self.radioButton_1.setFont(font)
        self.radioButton_1.setCursor(QCursor(Qt.PointingHandCursor))
        self.radioButton_1.setStyleSheet(u"color: rgb(0, 170, 0);")

        self.verticalLayout.addWidget(self.radioButton_1)

        self.radioButton_2 = QRadioButton(self.layoutWidget)
        self.radioButton_2.setObjectName(u"radioButton_2")
        self.radioButton_2.setFont(font)
        self.radioButton_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.radioButton_2.setStyleSheet(u"color: rgb(0, 170, 0);")

        self.verticalLayout.addWidget(self.radioButton_2)

        self.radioButton_3 = QRadioButton(self.layoutWidget)
        self.radioButton_3.setObjectName(u"radioButton_3")
        self.radioButton_3.setFont(font)
        self.radioButton_3.setCursor(QCursor(Qt.PointingHandCursor))
        self.radioButton_3.setStyleSheet(u"color: rgb(0, 170, 0);")

        self.verticalLayout.addWidget(self.radioButton_3)

        self.radioButton_4 = QRadioButton(self.layoutWidget)
        self.radioButton_4.setObjectName(u"radioButton_4")
        self.radioButton_4.setFont(font)
        self.radioButton_4.setCursor(QCursor(Qt.PointingHandCursor))
        self.radioButton_4.setStyleSheet(u"color: rgb(0, 170, 0);")

        self.verticalLayout.addWidget(self.radioButton_4)

        self.radioButton_5 = QRadioButton(self.layoutWidget)
        self.radioButton_5.setObjectName(u"radioButton_5")
        self.radioButton_5.setFont(font)
        self.radioButton_5.setCursor(QCursor(Qt.PointingHandCursor))
        self.radioButton_5.setStyleSheet(u"color: rgb(0, 170, 0);")

        self.verticalLayout.addWidget(self.radioButton_5)

        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(0, 0, 131, 71))
        self.label_9.setPixmap(QPixmap(u"../../../Downloads/icon.png"))
        self.label_9.setScaledContents(True)
        AD_COSTA_VERDE.setCentralWidget(self.centralwidget)

        self.retranslateUi(AD_COSTA_VERDE)

        QMetaObject.connectSlotsByName(AD_COSTA_VERDE)
    # setupUi

    def retranslateUi(self, AD_COSTA_VERDE):
        AD_COSTA_VERDE.setWindowTitle(qtTrId(u""))
#if QT_CONFIG(tooltip)
        AD_COSTA_VERDE.setToolTip(qtTrId(u""))
#endif // QT_CONFIG(tooltip)
        self.label.setText(qtTrId(u""))
        self.label_2.setText(qtTrId(u""))
        self.label_3.setText(qtTrId(u""))
        self.label_4.setText(qtTrId(u""))
        self.lineEdit_3.setText("")
        self.label_6.setText(qtTrId(u""))
        self.label_7.setText(qtTrId(u""))
        self.pushButton.setText(qtTrId(u""))
        self.pushButton_2.setText(qtTrId(u""))
        self.label_8.setText(qtTrId(u""))
        self.label_5.setText(qtTrId(u""))
        self.label_11.setText(qtTrId(u""))
        self.radioButton_1.setText(qtTrId(u""))
        self.radioButton_2.setText(qtTrId(u""))
        self.radioButton_3.setText(qtTrId(u""))
        self.radioButton_4.setText(qtTrId(u""))
        self.radioButton_5.setText(qtTrId(u""))
        self.label_9.setText("")
    # retranslateUi

